PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user (
	id INTEGER PRIMARY KEY NOT NULL,
	name VARCHAR(127) NOT NULL,
	username VARCHAR(127) UNIQUE NOT NULL,
	hashed_password BLOB,
	coupons INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_session (
	user_id INTEGER NOT NULL,
	token CHAR(32) UNIQUE NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user(id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS product (
	id INTEGER PRIMARY KEY NOT NULL,
	price INTEGER NOT NULL,
	name VARCHAR(127) NOT NULL,
	image VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS cart (
	user_id INTEGER NOT NULL,
	product_id INTEGER NOT NULL,
	amount INTEGER NOT NULL,
	PRIMARY KEY (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS history (
	user_id INTEGER NOT NULL,
	total INTEGER NOT NULL,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES user(id)
		ON DELETE CASCADE ON UPDATE CASCADE
);
